begin;
create type public.supplier_ledger_type as enum ('openingBalance','purchase','paymentMade','refund','adjustment');
create table public.suppliers(id uuid primary key,shop_id uuid not null references public.shops(id) on delete cascade,name text not null check(length(trim(name))>0),contact_person text,phone text,address text,notes text,is_active boolean not null default true,created_at timestamptz not null,updated_at timestamptz not null,unique(id,shop_id));
create table public.purchases(id uuid primary key,shop_id uuid not null references public.shops(id),supplier_id uuid not null,device_id uuid not null,invoice_number text,notes text,subtotal bigint not null check(subtotal>=0),discount_total bigint not null check(discount_total>=0),total bigint not null check(total>=0),paid_amount bigint not null check(paid_amount>=0 and paid_amount<=total),payment_status public.payment_status not null,created_by uuid not null,created_at timestamptz not null,aggregate_hash bytea,foreign key(supplier_id,shop_id) references public.suppliers(id,shop_id),foreign key(device_id,shop_id) references public.devices(id,shop_id),unique(id,shop_id));
create table public.purchase_items(id uuid primary key,shop_id uuid not null references public.shops(id),purchase_id uuid not null,product_id uuid not null,product_name_snapshot text not null,quantity bigint not null check(quantity>0),unit_cost bigint not null check(unit_cost>=0),line_total bigint not null check(line_total>=0),created_at timestamptz not null,foreign key(purchase_id,shop_id) references public.purchases(id,shop_id),foreign key(product_id,shop_id) references public.shop_products(id,shop_id));
create table public.purchase_payments(id uuid primary key,shop_id uuid not null references public.shops(id),purchase_id uuid not null,payment_method public.payment_method not null check(payment_method in ('cash','digital')),amount bigint not null check(amount>0),reference text,created_at timestamptz not null,foreign key(purchase_id,shop_id) references public.purchases(id,shop_id));
create table public.supplier_ledger_entries(id uuid primary key,shop_id uuid not null references public.shops(id),supplier_id uuid not null,type public.supplier_ledger_type not null,amount bigint not null check(amount>0),purchase_id uuid,payment_reference text,payment_method public.payment_method,note text,created_by uuid not null,created_at timestamptz not null,operation_hash bytea,foreign key(supplier_id,shop_id) references public.suppliers(id,shop_id),foreign key(purchase_id,shop_id) references public.purchases(id,shop_id),check((type='paymentMade' and payment_method in ('cash','digital')) or (type<>'paymentMade' and payment_method is null)));
create index suppliers_shop on public.suppliers(shop_id);
create index purchases_shop_created on public.purchases(shop_id,created_at desc);
create index purchase_items_purchase on public.purchase_items(purchase_id);
create index purchase_payments_purchase on public.purchase_payments(purchase_id);
create index supplier_ledger_lookup on public.supplier_ledger_entries(shop_id,supplier_id,created_at);
alter table public.suppliers enable row level security;alter table public.purchases enable row level security;alter table public.purchase_items enable row level security;alter table public.purchase_payments enable row level security;alter table public.supplier_ledger_entries enable row level security;
create policy suppliers_owner_select on public.suppliers for select to authenticated using(public.is_active_owner(shop_id));
create policy purchases_owner_select on public.purchases for select to authenticated using(public.is_active_owner(shop_id));
create policy purchase_items_owner_select on public.purchase_items for select to authenticated using(public.is_active_owner(shop_id));
create policy purchase_payments_owner_select on public.purchase_payments for select to authenticated using(public.is_active_owner(shop_id));
create policy supplier_ledger_owner_select on public.supplier_ledger_entries for select to authenticated using(public.is_active_owner(shop_id));
grant select on public.suppliers,public.purchases,public.purchase_items,public.purchase_payments,public.supplier_ledger_entries to authenticated;
create trigger suppliers_touch_updated_at before update on public.suppliers for each row execute function public.touch_updated_at();

create function public.save_supplier(p_shop_id uuid,p_supplier_id uuid,p_name text,p_contact_person text default null,p_phone text default null,p_address text default null,p_notes text default null,p_is_active boolean default true) returns uuid language plpgsql security definer set search_path=public,extensions,pg_temp as $$ declare v_id uuid:=coalesce(p_supplier_id,extensions.gen_random_uuid());begin if not public.is_active_owner(p_shop_id) then raise exception 'owner access required' using errcode='42501';end if;if length(trim(coalesce(p_name,'')))=0 then raise exception 'supplier name required';end if;if p_supplier_id is null then insert into public.suppliers(id,shop_id,name,contact_person,phone,address,notes,is_active,created_at,updated_at) values(v_id,p_shop_id,trim(p_name),nullif(trim(coalesce(p_contact_person,'')),''),nullif(trim(coalesce(p_phone,'')),''),nullif(trim(coalesce(p_address,'')),''),nullif(trim(coalesce(p_notes,'')),''),p_is_active,now(),now());else update public.suppliers set name=trim(p_name),contact_person=nullif(trim(coalesce(p_contact_person,'')),''),phone=nullif(trim(coalesce(p_phone,'')),''),address=nullif(trim(coalesce(p_address,'')),''),notes=nullif(trim(coalesce(p_notes,'')),''),is_active=p_is_active,updated_at=now() where id=p_supplier_id and shop_id=p_shop_id;if not found then raise exception 'supplier not found';end if;end if;return v_id;end $$;

create function public.sync_purchase_transaction(p_payload jsonb,p_cashier_token text default null) returns jsonb language plpgsql security definer set search_path=public,extensions,pg_temp as $$ declare p jsonb:=p_payload->'purchase';r jsonb;v_id uuid:=(p->>'id')::uuid;v_shop uuid:=(p->>'shopId')::uuid;v_supplier uuid:=(p->>'supplierId')::uuid;v_device uuid:=(p->>'deviceId')::uuid;v_hash bytea:=extensions.digest(convert_to(p_payload::text,'UTF8'),'sha256');v_old bytea;v_total bigint:=0;v_paid bigint:=0;v_due bigint:=0;begin perform pg_advisory_xact_lock(hashtextextended(v_id::text,0));if not public.is_active_owner(v_shop) then raise exception 'owner access required' using errcode='42501';end if;if not exists(select 1 from public.devices where id=v_device and shop_id=v_shop and is_active) then raise exception 'active device required' using errcode='42501';end if;if not exists(select 1 from public.suppliers where id=v_supplier and shop_id=v_shop and is_active) then raise exception 'active supplier required';end if;select aggregate_hash into v_old from public.purchases where id=v_id and shop_id=v_shop;if found then if v_old is null or v_old<>v_hash then raise exception 'conflicting replay for immutable purchase';end if;return jsonb_build_object('purchase_id',v_id,'status','already_synced');end if;
for r in select value from jsonb_array_elements(coalesce(p_payload->'purchase_items','[]')) loop if (r->>'quantity')::bigint<=0 or (r->>'unitCost')::bigint<0 then raise exception 'invalid purchase item';end if;if not exists(select 1 from public.shop_products where id=(r->>'productId')::uuid and shop_id=v_shop and is_active) then raise exception 'active product required';end if;v_total:=v_total+(r->>'lineTotal')::bigint;end loop;if jsonb_array_length(coalesce(p_payload->'purchase_items','[]'))=0 then raise exception 'purchase items required';end if;
for r in select value from jsonb_array_elements(coalesce(p_payload->'payments','[]')) loop if (r->>'paymentMethod') not in ('cash','digital') or (r->>'amount')::bigint<=0 then raise exception 'invalid purchase payment';end if;v_paid:=v_paid+(r->>'amount')::bigint;end loop;v_due:=v_total-v_paid;if v_due<0 or v_total<>(p->>'total')::bigint or v_paid<>(p->>'paidAmount')::bigint then raise exception 'purchase totals mismatch';end if;
insert into public.purchases(id,shop_id,supplier_id,device_id,invoice_number,notes,subtotal,discount_total,total,paid_amount,payment_status,created_by,created_at,aggregate_hash) values(v_id,v_shop,v_supplier,v_device,p->>'invoiceNumber',p->>'notes',(p->>'subtotal')::bigint,(p->>'discountTotal')::bigint,v_total,v_paid,(p->>'paymentStatus')::public.payment_status,(p->>'createdBy')::uuid,(p->>'createdAt')::timestamptz,v_hash);
for r in select value from jsonb_array_elements(p_payload->'purchase_items') loop insert into public.purchase_items values((r->>'id')::uuid,v_shop,v_id,(r->>'productId')::uuid,r->>'productNameSnapshot',(r->>'quantity')::bigint,(r->>'unitCost')::bigint,(r->>'lineTotal')::bigint,(r->>'createdAt')::timestamptz);end loop;
for r in select value from jsonb_array_elements(coalesce(p_payload->'payments','[]')) loop insert into public.purchase_payments values((r->>'id')::uuid,v_shop,v_id,(r->>'paymentMethod')::public.payment_method,(r->>'amount')::bigint,r->>'reference',(r->>'createdAt')::timestamptz);end loop;
for r in select value from jsonb_array_elements(p_payload->'inventory_movements') loop if (r->>'type')<>'purchase' or (r->>'quantity')::bigint<=0 then raise exception 'invalid stock movement';end if;insert into public.inventory_movements(id,shop_id,product_id,type,quantity,reference_type,reference_id,note,created_by,device_id,created_at) values((r->>'id')::uuid,v_shop,(r->>'productId')::uuid,'purchase',(r->>'quantity')::bigint,'purchase',v_id,r->>'note',(r->>'createdBy')::uuid,v_device,(r->>'createdAt')::timestamptz);end loop;
if v_due>0 then r:=(p_payload->'supplier_ledger_entries')->0; if r is null or (r->>'amount')::bigint<>v_due then raise exception 'supplier payable mismatch';end if;insert into public.supplier_ledger_entries(id,shop_id,supplier_id,type,amount,purchase_id,created_by,created_at,operation_hash) values((r->>'id')::uuid,v_shop,v_supplier,'purchase',v_due,v_id,(r->>'createdBy')::uuid,(r->>'createdAt')::timestamptz,v_hash);elsif jsonb_array_length(coalesce(p_payload->'supplier_ledger_entries','[]'))<>0 then raise exception 'unexpected supplier ledger entry';end if;
insert into public.audit_logs(id,shop_id,user_id,action,entity_type,entity_id,new_value,device_id,created_at) values((p_payload->>'audit_id')::uuid,v_shop,(p->>'createdBy')::uuid,'purchase.completed','purchase',v_id,jsonb_build_object('total',v_total,'paid',v_paid,'due',v_due),v_device,(p->>'createdAt')::timestamptz);return jsonb_build_object('purchase_id',v_id,'status','inserted');end $$;

create function public.sync_supplier_payment(p_payload jsonb,p_cashier_token text default null) returns jsonb language plpgsql security definer set search_path=public,extensions,pg_temp as $$ declare e jsonb:=p_payload->'entry';a jsonb:=p_payload->'audit';v_id uuid:=(e->>'id')::uuid;v_shop uuid:=(e->>'shop_id')::uuid;v_hash bytea:=extensions.digest(convert_to(p_payload::text,'UTF8'),'sha256');v_old bytea;begin perform pg_advisory_xact_lock(hashtextextended(v_id::text,0));if not public.is_active_owner(v_shop) then raise exception 'owner access required' using errcode='42501';end if;if (e->>'type')<>'paymentMade' or (e->>'amount')::bigint<=0 or (e->>'payment_method') not in ('cash','digital') then raise exception 'invalid supplier payment';end if;if not exists(select 1 from public.devices where id=(a->>'device_id')::uuid and shop_id=v_shop and is_active) then raise exception 'active device required' using errcode='42501';end if;if not exists(select 1 from public.suppliers where id=(e->>'supplier_id')::uuid and shop_id=v_shop and is_active) then raise exception 'active supplier required';end if;select operation_hash into v_old from public.supplier_ledger_entries where id=v_id and shop_id=v_shop;if found then if v_old is null or v_old<>v_hash then raise exception 'conflicting replay for immutable supplier payment';end if;return jsonb_build_object('entry_id',v_id,'status','already_synced');end if;insert into public.supplier_ledger_entries(id,shop_id,supplier_id,type,amount,payment_reference,payment_method,note,created_by,created_at,operation_hash) values(v_id,v_shop,(e->>'supplier_id')::uuid,'paymentMade',(e->>'amount')::bigint,e->>'payment_reference',(e->>'payment_method')::public.payment_method,e->>'note',(e->>'created_by')::uuid,(e->>'created_at')::timestamptz,v_hash);insert into public.audit_logs(id,shop_id,user_id,action,entity_type,entity_id,new_value,device_id,created_at) values((a->>'id')::uuid,v_shop,(e->>'created_by')::uuid,'supplier.payment_made','supplier_ledger_entry',v_id,a->'new_value',(a->>'device_id')::uuid,(a->>'created_at')::timestamptz);return jsonb_build_object('entry_id',v_id,'status','inserted');end $$;

revoke all on function public.save_supplier(uuid,uuid,text,text,text,text,text,boolean),public.sync_purchase_transaction(jsonb,text),public.sync_supplier_payment(jsonb,text) from public,anon,authenticated;
grant execute on function public.save_supplier(uuid,uuid,text,text,text,text,text,boolean),public.sync_purchase_transaction(jsonb,text),public.sync_supplier_payment(jsonb,text) to authenticated;
commit;
