begin;
create table public.expense_categories(id uuid primary key,shop_id uuid not null references public.shops(id) on delete cascade,name text not null check(length(trim(name))>0),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(shop_id,name),unique(id,shop_id));
create table public.expenses(id uuid primary key,shop_id uuid not null references public.shops(id),category_id uuid not null,category text not null,amount bigint not null check(amount>0),payment_method public.payment_method not null check(payment_method in('cash','digital')),expense_at timestamptz not null,description text not null check(length(trim(description))>0),note text,reference text,created_by uuid not null,device_id uuid not null,created_at timestamptz not null,operation_hash bytea,foreign key(category_id,shop_id) references public.expense_categories(id,shop_id),foreign key(device_id,shop_id) references public.devices(id,shop_id));
create index expenses_shop_date on public.expenses(shop_id,expense_at desc);
create index expenses_shop_category_date on public.expenses(shop_id,category_id,expense_at desc);
create index expenses_shop_method_date on public.expenses(shop_id,payment_method,expense_at desc);
alter table public.expense_categories enable row level security;alter table public.expenses enable row level security;
create policy expense_categories_owner_select on public.expense_categories for select to authenticated using(public.is_active_owner(shop_id));
create policy expenses_owner_select on public.expenses for select to authenticated using(public.is_active_owner(shop_id));
grant select on public.expense_categories,public.expenses to authenticated;
create trigger expense_categories_touch before update on public.expense_categories for each row execute function public.touch_updated_at();
create trigger expenses_owner_actor before insert on public.expenses for each row execute function public.enforce_owner_procurement_actor();

create function public.ensure_default_expense_categories(p_shop_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$declare n text;begin if not public.is_active_owner(p_shop_id)then raise exception 'owner access required' using errcode='42501';end if;foreach n in array array['Rent','Electricity','Gas','Internet','Salary','Transport','Delivery','Maintenance','Food/Tea','Packaging','Miscellaneous'] loop insert into public.expense_categories(id,shop_id,name)values(md5(p_shop_id::text||':expense:'||lower(n))::uuid,p_shop_id,n)on conflict(shop_id,name)do nothing;end loop;end$$;
create function public.create_expense_category(p_shop_id uuid,p_name text)returns uuid language plpgsql security definer set search_path=public,extensions,pg_temp as $$declare v uuid;begin if not public.is_active_owner(p_shop_id)then raise exception 'owner access required' using errcode='42501';end if;if length(trim(coalesce(p_name,'')))=0 then raise exception 'category name required';end if;insert into public.expense_categories(id,shop_id,name)values(extensions.gen_random_uuid(),p_shop_id,trim(p_name))on conflict(shop_id,name)do update set is_active=true,updated_at=now() returning id into v;return v;end$$;
create function public.sync_expense(p_payload jsonb,p_cashier_token text default null)returns jsonb language plpgsql security definer set search_path=public,extensions,pg_temp as $$declare e jsonb:=p_payload->'expense';a jsonb:=p_payload->'audit';v_id uuid:=(e->>'id')::uuid;v_shop uuid:=(e->>'shop_id')::uuid;v_hash bytea:=extensions.digest(convert_to(p_payload::text,'UTF8'),'sha256');v_old bytea;begin perform pg_advisory_xact_lock(hashtextextended(v_id::text,0));if not public.is_active_owner(v_shop)then raise exception 'owner access required' using errcode='42501';end if;if(e->>'created_by')::uuid<>auth.uid()then raise exception 'owner actor mismatch' using errcode='42501';end if;if(e->>'amount')::bigint<=0 or(e->>'payment_method')not in('cash','digital')or length(trim(coalesce(e->>'description','')))=0 then raise exception 'invalid expense';end if;if not exists(select 1 from public.devices where id=(e->>'device_id')::uuid and shop_id=v_shop and is_active)then raise exception 'active device required' using errcode='42501';end if;if not exists(select 1 from public.expense_categories where id=(e->>'category_id')::uuid and shop_id=v_shop and is_active)then raise exception 'active expense category required';end if;select operation_hash into v_old from public.expenses where id=v_id and shop_id=v_shop;if found then if v_old is null or v_old<>v_hash then raise exception 'conflicting replay for immutable expense';end if;return jsonb_build_object('expense_id',v_id,'status','already_synced');end if;insert into public.expenses(id,shop_id,category_id,category,amount,payment_method,expense_at,description,note,reference,created_by,device_id,created_at,operation_hash)values(v_id,v_shop,(e->>'category_id')::uuid,e->>'category',(e->>'amount')::bigint,(e->>'payment_method')::public.payment_method,(e->>'expense_at')::timestamptz,trim(e->>'description'),e->>'note',e->>'reference',(e->>'created_by')::uuid,(e->>'device_id')::uuid,(e->>'created_at')::timestamptz,v_hash);insert into public.audit_logs(id,shop_id,user_id,action,entity_type,entity_id,new_value,device_id,created_at)values((a->>'id')::uuid,v_shop,auth.uid(),'expense.created','expense',v_id,a->'new_value',(e->>'device_id')::uuid,(a->>'created_at')::timestamptz);return jsonb_build_object('expense_id',v_id,'status','inserted');end$$;
revoke all on function public.ensure_default_expense_categories(uuid),public.create_expense_category(uuid,text),public.sync_expense(jsonb,text) from public,anon,authenticated;
grant execute on function public.ensure_default_expense_categories(uuid),public.create_expense_category(uuid,text),public.sync_expense(jsonb,text) to authenticated;
commit;
